# Generated by Django 4.1 on 2022-08-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='prdadmin/'),
        ),
    ]
